### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by luantoningalvan** [luantoningalvan/ancaphub#3]
### Server
- [x] Configurações básicas
- [x] API de Livros
- [x] API de Cadastro/Login
- [x] API de Artigos
- [ ] API de Podcasts
- [ ] API de Upload
- [ ] Middleware para tratamento de erros 
- [ ] Middleware para proteção de rotas
... A ser incrementado

### Admin
- [x] Layout Base
- [x] Tela de Login
- [x] Rotas protegidas
- [ ] CRUD de Livros
  - [ ] Adição e Edição
    - [x] Campos de Título, Autor e Descrição
    - [x] Categorias
    - [ ] Capa com upload nativo
    - [ ] Opções de Download com upload nativo
  - [x] Exclusão
  - [x] Listagem
- [ ] CRUD de Artigos
- [ ] CRUD de Podcasts
- [ ] Componentes
  - [ ] Selecionar Categoria
    - [x] Listar todas categorias
    - [x] Integração com os valores do Formik
    - [ ] Excluir Categorias
  - [ ] Upload de Imagem
... A ser incrementado

### Web
- [x] Layout Base
- [ ] Página Inicial
- [ ] Módulo de Livros
  - [x] Listagem de todos os Livros
  - [x] Visualização de livro específico
  - [ ] Sistema de download nativo 
  - [ ] Avaliar livro
  - [ ] Compartilhar livro
  - [x] Adicionar livro aos favoritos
  - [ ] Comentar livro
  - [ ] Adicionar contribuição
- [x] Módulo de Artigos
- [ ] Módulo de Podcasts
- [x] Perfil do Usuário
- [ ] Feed de Notícias
- [ ] Sistema de Notificações
- [ ] Sistema de Mensagens
- [ ] Sistema de Busca
... A ser incrementado

### App
Em breve
